import { useState, useCallback, useEffect, useRef } from 'react'

const STORAGE_PREFIX = 'toolchain_language_'

export const LANGUAGES = [
  { id: 'en', label: 'English', flag: '🇺🇸' },
  { id: 'ur', label: 'اردو', flag: '🇵🇰' },
  { id: 'ar', label: 'العربية', flag: '🇸🇦' },
  { id: 'hi', label: 'हिन्दी', flag: '🇮🇳' },
  { id: 'zh', label: '中文', flag: '🇨🇳' },
  { id: 'es', label: 'Español', flag: '🇪🇸' },
  { id: 'fr', label: 'Français', flag: '🇫🇷' },
  { id: 'de', label: 'Deutsch', flag: '🇩🇪' },
  { id: 'pt', label: 'Português', flag: '🇧🇷' },
  { id: 'tr', label: 'Türkçe', flag: '🇹🇷' },
  { id: 'ja', label: '日本語', flag: '🇯🇵' },
  { id: 'ko', label: '한국어', flag: '🇰🇷' },
  { id: 'ru', label: 'Русский', flag: '🇷🇺' },
]

const translations = {
  en: {
    settings: 'Settings',
    customize: 'Customize your experience',
    general: 'General',
    account: 'Account',
    security: 'Security',
    chatSessions: 'Chat Sessions',
    appearance: 'Appearance',
    lightTheme: 'Light',
    darkTheme: 'Dark',
    lightDesc: 'Clean and bright interface',
    darkDesc: 'Easy on the eyes',
    language: 'Language',
    selectLanguage: 'Select your preferred language',
    accentColor: 'Accent Color',
    customizeAccent: 'Personalize app colors',
    defaultColor: 'Default',
    personalInfo: 'Personal Information',
    viewDetails: 'View your details',
    email: 'Email',
    username: 'Username',
    fullName: 'Full Name',
    notSet: 'Not set',
    memberSince: 'Member Since',
    manageCredentials: 'Manage your credentials',
    changeUsername: 'Change Username',
    changePassword: 'Change Password',
    updatePassword: 'Update your account password',
    newUsername: 'New Username',
    enterNewUsername: 'Enter new username',
    save: 'Save',
    cancel: 'Cancel',
    currentPassword: 'Current Password',
    enterCurrentPassword: 'Enter current password',
    newPassword: 'New Password',
    enterNewPassword: 'Enter new password',
    confirmNewPassword: 'Confirm New Password',
    confirmNewPasswordPlaceholder: 'Confirm new password',
    updatePasswordBtn: 'Update Password',
    passwordsDontMatch: 'Passwords do not match',
    passwordSameAsCurrent: 'New password must be different from current password',
    exportOrDelete: 'Export or delete your conversations',
    exportAllChats: 'Export All Chats',
    downloadWord: 'Download as Word document',
    exportDesc: 'Export all your conversations to a <strong>.docx</strong> Word file. Each session will include the full message history with timestamps.',
    export: 'Export',
    deleteAllChats: 'Delete All Chats',
    permanentlyRemove: 'Permanently remove all conversations',
    deleteWarning: 'This action is <strong>permanent</strong> and cannot be undone. All your chat sessions and messages will be deleted.',
    typeDelete: 'Type <strong>DELETE</strong> to confirm',
    deleteAll: 'Delete All',
    done: 'Done',
    pleaseWait: 'Please wait...',
    chars8: '8+ characters',
    uppercase: 'Uppercase',
    lowercase: 'Lowercase',
    number: 'Number',
    specialChar: 'Special char',
    dashboard: 'Dashboard',
    mcpServers: 'MCP Servers',
    chat: 'Chat',
    newChat: 'New Chat',
    signOut: 'Sign Out',
    toolchainAI: 'ToolChain AI',
    welcomeSubtitle: 'Connect MCP servers and chat with an AI agent that uses their tools.',
    connectedInfo: '{count} MCP server{s} connected',
    noConversations: 'No conversations yet',
    newConversation: 'New conversation',
    today: 'Today',
    yesterday: 'Yesterday',
    thisWeek: 'This Week',
    older: 'Older',
    goodMorning: 'Good Morning',
    goodAfternoon: 'Good Afternoon',
    goodEvening: 'Good Evening',
    activeReady: 'active and ready',
    waitingConnections: 'waiting for connections',
    serversConnected: '{count} server{s} connected and processing.',
    connectToStart: 'Connect an MCP server to get started.',
    quickActions: 'Quick Actions',
    addServer: 'Add Server',
    startConversation: 'Start a conversation with AI',
    registerNewMcp: 'Register a new MCP server',
    manageServers: 'Manage Servers',
    viewConfigureMcps: 'View and configure MCPs',
    activityOverview: 'Activity Overview',
    weeklyActivity: 'Weekly Activity',
    messages: 'Messages',
    sessions: 'Sessions',
    totalMessages: 'Total Messages',
    totalSessions: 'Total Sessions',
    uptime: 'Uptime',
    health: 'Health',
    viewAll: 'View All',
    noServersRegistered: 'No servers registered yet',
    registerServer: 'Register Server',
    active: 'Active',
    offline: 'Offline',
    moreServers: '+{count} more servers',
    recentChats: 'Recent Chats',
    startChat: 'Start Chat',
    aiPowerTips: 'AI Power Tips',
    getMoreFromAi: 'Get more from ToolChain AI',
    multiLanguageSupport: 'Multi-language Support',
    multiLanguageDesc: 'Chat in English, Urdu, Hindi or mixed — AI understands all',
    bulkActions: 'Bulk Actions',
    bulkActionsDesc: 'Say "trash all emails from X" — AI handles multi-step tasks',
    smartSearch: 'Smart Search',
    smartSearchDesc: 'Use Gmail syntax: "from:x@y.com", "newer_than:7d"',
    tryItNow: 'Try it now',
    systemsOnline: 'Systems Online',
    suggestion1: 'What tools are available?',
    suggestion2: 'Tell me about the connected MCP servers',
    suggestion3: 'What can you help me with?',
    suggestion4: 'Run a quick test with available tools',
    typeMessage: 'Type a message...',
    serversRunning: '{connected}/{total} servers running',
    toolExecution: 'Tool Execution',
    toolExecSubtitle: 'Test and execute MCP tools directly',
    noConnectedMcps: 'No Connected Servers',
    noConnectedMcpsDesc: 'Connect an MCP server first to test its tools here.',
    goToMcpServers: 'Go to MCP Servers',
  },
  ur: {
    settings: 'ترتیبات',
    customize: 'اپنے تجربے کو حسب ضرورت بنائیں',
    general: 'عمومی',
    account: 'اکاؤنٹ',
    security: 'سیکیورٹی',
    chatSessions: 'چیٹ سیشنز',
    appearance: 'ظاہری شکل',
    lightTheme: 'لائٹ',
    darkTheme: 'ڈارک',
    lightDesc: 'صاف اور روشن انٹرفیس',
    darkDesc: 'آنکھوں پر آسان',
    language: 'زبان',
    selectLanguage: 'اپنی پسندیدہ زبان منتخب کریں',
    accentColor: 'ایکسنٹ رنگ',
    customizeAccent: 'ایپ کے رنگ حسب ضرورت بنائیں',
    defaultColor: 'ڈیفالٹ',
    personalInfo: 'ذاتی معلومات',
    viewDetails: 'اپنی تفصیلات دیکھیں',
    email: 'ای میل',
    username: 'صارف نام',
    fullName: 'پورا نام',
    notSet: 'سیٹ نہیں',
    memberSince: 'ممبر از',
    manageCredentials: 'اپنی اسناد کا نظم کریں',
    changeUsername: 'صارف نام تبدیل کریں',
    changePassword: 'پاسورڈ تبدیل کریں',
    updatePassword: 'اپنے اکاؤنٹ کا پاسورڈ اپ ڈیٹ کریں',
    newUsername: 'نیا صارف نام',
    enterNewUsername: 'نیا صارف نام درج کریں',
    save: 'محفوظ کریں',
    cancel: 'منسوخ',
    currentPassword: 'موجودہ پاسورڈ',
    enterCurrentPassword: 'موجودہ پاسورڈ درج کریں',
    newPassword: 'نیا پاسورڈ',
    enterNewPassword: 'نیا پاسورڈ درج کریں',
    confirmNewPassword: 'نئے پاسورڈ کی تصدیق',
    confirmNewPasswordPlaceholder: 'نئے پاسورڈ کی تصدیق کریں',
    updatePasswordBtn: 'پاسورڈ اپ ڈیٹ کریں',
    passwordsDontMatch: 'پاسورڈ مماثل نہیں ہیں',
    passwordSameAsCurrent: 'نیا پاسورڈ موجودہ پاسورڈ سے مختلف ہونا چاہیے',
    exportOrDelete: 'اپنی گفتگو ایکسپورٹ یا ڈیلیٹ کریں',
    exportAllChats: 'تمام چیٹس ایکسپورٹ',
    downloadWord: 'ورڈ دستاویز کے طور پر ڈاؤن لوڈ',
    exportDesc: 'تمام گفتگو <strong>.docx</strong> ورڈ فائل میں ایکسپورٹ کریں۔',
    export: 'ایکسپورٹ',
    deleteAllChats: 'تمام چیٹس ڈیلیٹ',
    permanentlyRemove: 'تمام گفتگو مستقل طور پر ہٹائیں',
    deleteWarning: 'یہ عمل <strong>مستقل</strong> ہے اور واپس نہیں ہو سکتا۔',
    typeDelete: '<strong>DELETE</strong> ٹائپ کر کے تصدیق کریں',
    deleteAll: 'سب ڈیلیٹ',
    done: 'ہو گیا',
    pleaseWait: 'براہ کرم انتظار کریں...',
    chars8: '8+ حروف',
    uppercase: 'بڑے حروف',
    lowercase: 'چھوٹے حروف',
    number: 'نمبر',
    specialChar: 'خاص حرف',
    dashboard: 'ڈیش بورڈ',
    mcpServers: 'MCP سرورز',
    chat: 'چیٹ',
    newChat: 'نئی چیٹ',
    signOut: 'لاگ آؤٹ',
    toolchainAI: 'ToolChain AI',
    welcomeSubtitle: 'MCP سرورز کنیکٹ کریں اور AI ایجنٹ سے چیٹ کریں۔',
    connectedInfo: '{count} MCP سرور کنیکٹ',
    noConversations: 'ابھی تک کوئی گفتگو نہیں',
    newConversation: 'نئی گفتگو',
    today: 'آج',
    yesterday: 'کل',
    thisWeek: 'اس ہفتے',
    older: 'پرانی',
    goodMorning: 'صبح بخیر',
    goodAfternoon: 'سہ پہر بخیر',
    goodEvening: 'شام بخیر',
    activeReady: 'فعال اور تیار',
    waitingConnections: 'کنکشنز کا انتظار',
    serversConnected: '{count} سرور کنیکٹ اور فعال۔',
    connectToStart: 'شروع کرنے کے لیے MCP سرور کنیکٹ کریں۔',
    quickActions: 'فوری اقدامات',
    addServer: 'سرور شامل کریں',
    startConversation: 'AI سے بات چیت شروع کریں',
    registerNewMcp: 'نیا MCP سرور رجسٹر کریں',
    manageServers: 'سرورز کا انتظام',
    viewConfigureMcps: 'MCPs دیکھیں اور ترتیب دیں',
    activityOverview: 'سرگرمی کا جائزہ',
    weeklyActivity: 'ہفتہ وار سرگرمی',
    messages: 'پیغامات',
    sessions: 'سیشنز',
    totalMessages: 'کل پیغامات',
    totalSessions: 'کل سیشنز',
    uptime: 'اپ ٹائم',
    health: 'صحت',
    viewAll: 'سب دیکھیں',
    noServersRegistered: 'ابھی تک کوئی سرور رجسٹر نہیں',
    registerServer: 'سرور رجسٹر کریں',
    active: 'فعال',
    offline: 'آف لائن',
    moreServers: '+{count} مزید سرورز',
    recentChats: 'حالیہ چیٹس',
    startChat: 'چیٹ شروع کریں',
    aiPowerTips: 'AI پاور ٹپس',
    getMoreFromAi: 'ToolChain AI سے مزید حاصل کریں',
    multiLanguageSupport: 'کثیر زبان سپورٹ',
    multiLanguageDesc: 'انگریزی، اردو، ہندی یا ملا جلا — AI سب سمجھتا ہے',
    bulkActions: 'بلک اقدامات',
    bulkActionsDesc: '"X سے تمام ای میلز ڈیلیٹ کرو" — AI کئی مراحل سنبھالتا ہے',
    smartSearch: 'سمارٹ سرچ',
    smartSearchDesc: 'Gmail سنٹیکس استعمال کریں: "from:x@y.com", "newer_than:7d"',
    tryItNow: 'ابھی آزمائیں',
    systemsOnline: 'سسٹمز آن لائن',
    suggestion1: 'کون سے ٹولز دستیاب ہیں؟',
    suggestion2: 'کنیکٹڈ MCP سرورز کے بارے میں بتائیں',
    suggestion3: 'آپ مجھے کس میں مدد کر سکتے ہیں؟',
    suggestion4: 'دستیاب ٹولز سے فوری ٹیسٹ چلائیں',
    typeMessage: 'پیغام لکھیں...',
    serversRunning: '{connected}/{total} سرورز چل رہے ہیں',
    toolExecution: 'ٹول ایگزیکیوشن',
    toolExecSubtitle: 'MCP ٹولز براہ راست ٹیسٹ اور چلائیں',
    noConnectedMcps: 'کوئی سرور کنیکٹ نہیں',
    noConnectedMcpsDesc: 'ٹولز ٹیسٹ کرنے کے لیے پہلے MCP سرور کنیکٹ کریں۔',
    goToMcpServers: 'MCP سرورز پر جائیں',
  },
  ar: {
    settings: 'الإعدادات', customize: 'تخصيص تجربتك', general: 'عام', account: 'الحساب', security: 'الأمان', chatSessions: 'جلسات الدردشة', appearance: 'المظهر', lightTheme: 'فاتح', darkTheme: 'داكن', lightDesc: 'واجهة نظيفة ومشرقة', darkDesc: 'مريح للعيون', language: 'اللغة', selectLanguage: 'اختر لغتك المفضلة', accentColor: 'لون التمييز', customizeAccent: 'تخصيص ألوان التطبيق', defaultColor: 'افتراضي', personalInfo: 'المعلومات الشخصية', viewDetails: 'عرض تفاصيلك', email: 'البريد الإلكتروني', username: 'اسم المستخدم', fullName: 'الاسم الكامل', notSet: 'غير محدد', memberSince: 'عضو منذ', manageCredentials: 'إدارة بيانات الاعتماد', changeUsername: 'تغيير اسم المستخدم', changePassword: 'تغيير كلمة المرور', updatePassword: 'تحديث كلمة مرور حسابك', newUsername: 'اسم مستخدم جديد', enterNewUsername: 'أدخل اسم مستخدم جديد', save: 'حفظ', cancel: 'إلغاء', currentPassword: 'كلمة المرور الحالية', enterCurrentPassword: 'أدخل كلمة المرور الحالية', newPassword: 'كلمة المرور الجديدة', enterNewPassword: 'أدخل كلمة المرور الجديدة', confirmNewPassword: 'تأكيد كلمة المرور', confirmNewPasswordPlaceholder: 'تأكيد كلمة المرور الجديدة', updatePasswordBtn: 'تحديث كلمة المرور', passwordsDontMatch: 'كلمات المرور غير متطابقة', passwordSameAsCurrent: 'يجب أن تختلف كلمة المرور الجديدة عن الحالية', exportOrDelete: 'تصدير أو حذف محادثاتك', exportAllChats: 'تصدير جميع الدردشات', downloadWord: 'تنزيل كمستند Word', exportDesc: 'تصدير جميع محادثاتك إلى ملف <strong>.docx</strong>', export: 'تصدير', deleteAllChats: 'حذف جميع الدردشات', permanentlyRemove: 'إزالة جميع المحادثات نهائياً', deleteWarning: 'هذا الإجراء <strong>نهائي</strong> ولا يمكن التراجع عنه.', typeDelete: 'اكتب <strong>DELETE</strong> للتأكيد', deleteAll: 'حذف الكل', done: 'تم', pleaseWait: 'يرجى الانتظار...', chars8: '8+ أحرف', uppercase: 'أحرف كبيرة', lowercase: 'أحرف صغيرة', number: 'رقم', specialChar: 'حرف خاص', dashboard: 'لوحة القيادة', mcpServers: 'خوادم MCP', chat: 'دردشة', newChat: 'دردشة جديدة', signOut: 'تسجيل الخروج', toolchainAI: 'ToolChain AI', welcomeSubtitle: 'اربط خوادم MCP وتحدث مع وكيل الذكاء الاصطناعي.', connectedInfo: '{count} خادم MCP متصل', noConversations: 'لا توجد محادثات بعد', newConversation: 'محادثة جديدة', today: 'اليوم', yesterday: 'أمس', thisWeek: 'هذا الأسبوع', older: 'أقدم', goodMorning: 'صباح الخير', goodAfternoon: 'نهارك سعيد', goodEvening: 'مساء الخير', activeReady: 'نشط وجاهز', waitingConnections: 'في انتظار الاتصالات', serversConnected: '{count} خادم{s} متصل ويعالج.', connectToStart: 'اربط خادم MCP للبدء.', quickActions: 'إجراءات سريعة', addServer: 'إضافة خادم', startConversation: 'ابدأ محادثة مع الذكاء الاصطناعي', registerNewMcp: 'تسجيل خادم MCP جديد', manageServers: 'إدارة الخوادم', viewConfigureMcps: 'عرض وتكوين MCPs', activityOverview: 'نظرة عامة على النشاط', weeklyActivity: 'النشاط الأسبوعي', messages: 'الرسائل', sessions: 'الجلسات', totalMessages: 'إجمالي الرسائل', totalSessions: 'إجمالي الجلسات', uptime: 'وقت التشغيل', health: 'الصحة', viewAll: 'عرض الكل', noServersRegistered: 'لا توجد خوادم مسجلة بعد', registerServer: 'تسجيل خادم', active: 'نشط', offline: 'غير متصل', moreServers: '+{count} خوادم إضافية', recentChats: 'الدردشات الأخيرة', startChat: 'بدء الدردشة', aiPowerTips: 'نصائح قوة الذكاء الاصطناعي', getMoreFromAi: 'احصل على المزيد من ToolChain AI', multiLanguageSupport: 'دعم متعدد اللغات', multiLanguageDesc: 'تحدث بالإنجليزية أو الأردو أو الهندية أو مخلوطًا — الذكاء الاصطناعي يفهم كل ذلك', bulkActions: 'إجراءات جماعية', bulkActionsDesc: 'قل "احذف كل رسائل X" — الذكاء الاصطناعي يتعامل مع المهام متعددة الخطوات', smartSearch: 'بحث ذكي', smartSearchDesc: 'استخدم صيغة Gmail: "from:x@y.com", "newer_than:7d"', tryItNow: 'جرّب الآن', systemsOnline: 'الأنظمة متصلة', suggestion1: 'ما الأدوات المتاحة؟', suggestion2: 'أخبرني عن خوادم MCP المتصلة', suggestion3: 'بماذا يمكنك مساعدتي؟', suggestion4: 'شغّل اختبارًا سريعًا بالأدوات المتاحة', typeMessage: 'اكتب رسالة...', serversRunning: '{connected}/{total} خادم يعمل', toolExecution: 'تنفيذ الأدوات', toolExecSubtitle: 'اختبار وتنفيذ أدوات MCP مباشرة', noConnectedMcps: 'لا توجد خوادم متصلة', noConnectedMcpsDesc: 'اربط خادم MCP أولاً لاختبار أدواته هنا.', goToMcpServers: 'انتقل إلى خوادم MCP',
  },
  hi: {
    settings: 'सेटिंग्स', customize: 'अपने अनुभव को कस्टमाइज़ करें', general: 'सामान्य', account: 'खाता', security: 'सुरक्षा', chatSessions: 'चैट सत्र', appearance: 'दिखावट', lightTheme: 'लाइट', darkTheme: 'डार्क', lightDesc: 'साफ़ और चमकदार इंटरफ़ेस', darkDesc: 'आँखों पर आसान', language: 'भाषा', selectLanguage: 'अपनी पसंदीदा भाषा चुनें', accentColor: 'एक्सेंट रंग', customizeAccent: 'ऐप के रंग बदलें', defaultColor: 'डिफ़ॉल्ट', personalInfo: 'व्यक्तिगत जानकारी', viewDetails: 'अपनी जानकारी देखें', email: 'ईमेल', username: 'उपयोगकर्ता नाम', fullName: 'पूरा नाम', notSet: 'सेट नहीं', memberSince: 'सदस्य तब से', manageCredentials: 'अपनी साख प्रबंधित करें', changeUsername: 'उपयोगकर्ता नाम बदलें', changePassword: 'पासवर्ड बदलें', updatePassword: 'अपना पासवर्ड अपडेट करें', newUsername: 'नया उपयोगकर्ता नाम', enterNewUsername: 'नया उपयोगकर्ता नाम दर्ज करें', save: 'सेव', cancel: 'रद्द', currentPassword: 'वर्तमान पासवर्ड', enterCurrentPassword: 'वर्तमान पासवर्ड दर्ज करें', newPassword: 'नया पासवर्ड', enterNewPassword: 'नया पासवर्ड दर्ज करें', confirmNewPassword: 'नया पासवर्ड पुष्टि करें', confirmNewPasswordPlaceholder: 'नया पासवर्ड पुष्टि करें', updatePasswordBtn: 'पासवर्ड अपडेट करें', passwordsDontMatch: 'पासवर्ड मेल नहीं खाते', passwordSameAsCurrent: 'नया पासवर्ड वर्तमान से अलग होना चाहिए', exportOrDelete: 'अपनी बातचीत एक्सपोर्ट या डिलीट करें', exportAllChats: 'सभी चैट एक्सपोर्ट', downloadWord: 'Word दस्तावेज़ के रूप में डाउनलोड', exportDesc: 'सभी बातचीत <strong>.docx</strong> फ़ाइल में एक्सपोर्ट करें।', export: 'एक्सपोर्ट', deleteAllChats: 'सभी चैट डिलीट', permanentlyRemove: 'सभी बातचीत स्थायी रूप से हटाएँ', deleteWarning: 'यह कार्रवाई <strong>स्थायी</strong> है और पूर्ववत नहीं की जा सकती।', typeDelete: 'पुष्टि के लिए <strong>DELETE</strong> टाइप करें', deleteAll: 'सब डिलीट', done: 'हो गया', pleaseWait: 'कृपया प्रतीक्षा करें...', chars8: '8+ अक्षर', uppercase: 'बड़े अक्षर', lowercase: 'छोटे अक्षर', number: 'संख्या', specialChar: 'विशेष वर्ण', dashboard: 'डैशबोर्ड', mcpServers: 'MCP सर्वर', chat: 'चैट', newChat: 'नई चैट', signOut: 'साइन आउट', toolchainAI: 'ToolChain AI', welcomeSubtitle: 'MCP सर्वर कनेक्ट करें और AI एजेंट से चैट करें।', connectedInfo: '{count} MCP सर्वर कनेक्टेड', noConversations: 'अभी तक कोई बातचीत नहीं', newConversation: 'नई बातचीत', today: 'आज', yesterday: 'कल', thisWeek: 'इस सप्ताह', older: 'पुराना', goodMorning: 'सुप्रभात', goodAfternoon: 'शुभ दोपहर', goodEvening: 'शुभ संध्या', activeReady: 'सक्रिय और तैयार', waitingConnections: 'कनेक्शन की प्रतीक्षा', serversConnected: '{count} सर्वर{s} कनेक्ट और प्रोसेसिंग में।', connectToStart: 'शुरू करने के लिए MCP सर्वर कनेक्ट करें।', quickActions: 'त्वरित कार्य', addServer: 'सर्वर जोड़ें', startConversation: 'AI से बातचीत शुरू करें', registerNewMcp: 'नया MCP सर्वर पंजीकृत करें', manageServers: 'सर्वर प्रबंधित करें', viewConfigureMcps: 'MCP देखें और कॉन्फ़िगर करें', activityOverview: 'गतिविधि अवलोकन', weeklyActivity: 'साप्ताहिक गतिविधि', messages: 'संदेश', sessions: 'सत्र', totalMessages: 'कुल संदेश', totalSessions: 'कुल सत्र', uptime: 'अपटाइम', health: 'स्वास्थ्य', viewAll: 'सभी देखें', noServersRegistered: 'अभी तक कोई सर्वर पंजीकृत नहीं', registerServer: 'सर्वर पंजीकृत करें', active: 'सक्रिय', offline: 'ऑफ़लाइन', moreServers: '+{count} और सर्वर', recentChats: 'हाल की चैट', startChat: 'चैट शुरू करें', aiPowerTips: 'AI पावर टिप्स', getMoreFromAi: 'ToolChain AI से और अधिक पाएँ', multiLanguageSupport: 'बहुभाषी सहायता', multiLanguageDesc: 'अंग्रेज़ी, उर्दू, हिंदी या मिश्रित में चैट करें — AI सब समझता है', bulkActions: 'बल्क कार्य', bulkActionsDesc: 'कहें "X से सभी ईमेल ट्रैश करो" — AI बहु-चरण कार्य संभालता है', smartSearch: 'स्मार्ट खोज', smartSearchDesc: 'Gmail सिंटैक्स: "from:x@y.com", "newer_than:7d"', tryItNow: 'अभी आज़माएँ', systemsOnline: 'सिस्टम ऑनलाइन', suggestion1: 'कौन से टूल उपलब्ध हैं?', suggestion2: 'कनेक्टेड MCP सर्वरों के बारे में बताएँ', suggestion3: 'आप मेरी कैसे मदद कर सकते हैं?', suggestion4: 'उपलब्ध टूल के साथ त्वरित परीक्षण चलाएँ', typeMessage: 'संदेश लिखें...', serversRunning: '{connected}/{total} सर्वर चल रहे हैं', toolExecution: 'टूल एक्जीक्यूशन', toolExecSubtitle: 'MCP टूल्स सीधे टेस्ट और एक्जीक्यूट करें', noConnectedMcps: 'कोई सर्वर कनेक्ट नहीं', noConnectedMcpsDesc: 'यहाँ टूल्स टेस्ट करने के लिए पहले MCP सर्वर कनेक्ट करें।', goToMcpServers: 'MCP सर्वर पर जाएँ',
  },
  zh: {
    settings: '设置', customize: '自定义您的体验', general: '常规', account: '账户', security: '安全', chatSessions: '聊天会话', appearance: '外观', lightTheme: '浅色', darkTheme: '深色', lightDesc: '简洁明亮的界面', darkDesc: '护眼模式', language: '语言', selectLanguage: '选择您的首选语言', accentColor: '强调色', customizeAccent: '个性化应用颜色', defaultColor: '默认', personalInfo: '个人信息', viewDetails: '查看您的详细信息', email: '邮箱', username: '用户名', fullName: '全名', notSet: '未设置', memberSince: '注册时间', manageCredentials: '管理您的凭据', changeUsername: '更改用户名', changePassword: '更改密码', updatePassword: '更新账户密码', newUsername: '新用户名', enterNewUsername: '输入新用户名', save: '保存', cancel: '取消', currentPassword: '当前密码', enterCurrentPassword: '输入当前密码', newPassword: '新密码', enterNewPassword: '输入新密码', confirmNewPassword: '确认新密码', confirmNewPasswordPlaceholder: '确认新密码', updatePasswordBtn: '更新密码', passwordsDontMatch: '密码不匹配', passwordSameAsCurrent: '新密码必须与当前密码不同', exportOrDelete: '导出或删除您的对话', exportAllChats: '导出所有聊天', downloadWord: '下载为Word文档', exportDesc: '将所有对话导出为<strong>.docx</strong>文件。', export: '导出', deleteAllChats: '删除所有聊天', permanentlyRemove: '永久删除所有对话', deleteWarning: '此操作<strong>不可逆</strong>，无法撤销。', typeDelete: '输入<strong>DELETE</strong>确认', deleteAll: '全部删除', done: '完成', pleaseWait: '请稍候...', chars8: '8+字符', uppercase: '大写字母', lowercase: '小写字母', number: '数字', specialChar: '特殊字符', dashboard: '仪表板', mcpServers: 'MCP服务器', chat: '聊天', newChat: '新聊天', signOut: '退出', toolchainAI: 'ToolChain AI', welcomeSubtitle: '连接MCP服务器并与AI代理聊天。', connectedInfo: '{count}个MCP服务器已连接', noConversations: '暂无对话', newConversation: '新对话', today: '今天', yesterday: '昨天', thisWeek: '本周', older: '更早', goodMorning: '早上好', goodAfternoon: '下午好', goodEvening: '晚上好', activeReady: '活跃并就绪', waitingConnections: '等待连接', serversConnected: '{count} 台服务器{s}已连接并处理中。', connectToStart: '连接 MCP 服务器以开始使用。', quickActions: '快捷操作', addServer: '添加服务器', startConversation: '与 AI 开始对话', registerNewMcp: '注册新的 MCP 服务器', manageServers: '管理服务器', viewConfigureMcps: '查看和配置 MCP', activityOverview: '活动概览', weeklyActivity: '每周活动', messages: '消息', sessions: '会话', totalMessages: '总消息数', totalSessions: '总会话数', uptime: '运行时间', health: '健康状况', viewAll: '查看全部', noServersRegistered: '尚未注册服务器', registerServer: '注册服务器', active: '在线', offline: '离线', moreServers: '+{count} 更多服务器', recentChats: '最近聊天', startChat: '开始聊天', aiPowerTips: 'AI 实用技巧', getMoreFromAi: '充分发挥 ToolChain AI', multiLanguageSupport: '多语言支持', multiLanguageDesc: '用英语、乌尔都语、印地语或混合语种聊天——AI 都能理解', bulkActions: '批量操作', bulkActionsDesc: '说「删除来自 X 的所有邮件」——AI 处理多步骤任务', smartSearch: '智能搜索', smartSearchDesc: '使用 Gmail 语法："from:x@y.com"、"newer_than:7d"', tryItNow: '立即试用', systemsOnline: '系统在线', suggestion1: '有哪些工具可用？', suggestion2: '介绍一下已连接的 MCP 服务器', suggestion3: '你能帮我做什么？', suggestion4: '用可用工具运行快速测试', typeMessage: '输入消息...', serversRunning: '{connected}/{total} 台服务器运行中', toolExecution: '工具执行', toolExecSubtitle: '直接测试和执行MCP工具', noConnectedMcps: '没有已连接的服务器', noConnectedMcpsDesc: '请先连接MCP服务器以测试其工具。', goToMcpServers: '前往MCP服务器',
  },
  es: {
    settings: 'Configuración', customize: 'Personaliza tu experiencia', general: 'General', account: 'Cuenta', security: 'Seguridad', chatSessions: 'Sesiones de Chat', appearance: 'Apariencia', lightTheme: 'Claro', darkTheme: 'Oscuro', lightDesc: 'Interfaz limpia y brillante', darkDesc: 'Fácil para los ojos', language: 'Idioma', selectLanguage: 'Selecciona tu idioma preferido', accentColor: 'Color de acento', customizeAccent: 'Personalizar colores de la app', defaultColor: 'Predeterminado', personalInfo: 'Información Personal', viewDetails: 'Ver tus detalles', email: 'Correo', username: 'Usuario', fullName: 'Nombre Completo', notSet: 'No establecido', memberSince: 'Miembro desde', manageCredentials: 'Gestionar tus credenciales', changeUsername: 'Cambiar Usuario', changePassword: 'Cambiar Contraseña', updatePassword: 'Actualiza tu contraseña', newUsername: 'Nuevo Usuario', enterNewUsername: 'Ingresa nuevo usuario', save: 'Guardar', cancel: 'Cancelar', currentPassword: 'Contraseña Actual', enterCurrentPassword: 'Ingresa contraseña actual', newPassword: 'Nueva Contraseña', enterNewPassword: 'Ingresa nueva contraseña', confirmNewPassword: 'Confirmar Contraseña', confirmNewPasswordPlaceholder: 'Confirmar nueva contraseña', updatePasswordBtn: 'Actualizar Contraseña', passwordsDontMatch: 'Las contraseñas no coinciden', passwordSameAsCurrent: 'La nueva contraseña debe ser diferente', exportOrDelete: 'Exportar o eliminar tus conversaciones', exportAllChats: 'Exportar Todos los Chats', downloadWord: 'Descargar como documento Word', exportDesc: 'Exportar todas las conversaciones a un archivo <strong>.docx</strong>.', export: 'Exportar', deleteAllChats: 'Eliminar Todos los Chats', permanentlyRemove: 'Eliminar permanentemente', deleteWarning: 'Esta acción es <strong>permanente</strong> e irreversible.', typeDelete: 'Escribe <strong>DELETE</strong> para confirmar', deleteAll: 'Eliminar Todo', done: 'Listo', pleaseWait: 'Espera por favor...', chars8: '8+ caracteres', uppercase: 'Mayúsculas', lowercase: 'Minúsculas', number: 'Número', specialChar: 'Carácter especial', dashboard: 'Panel', mcpServers: 'Servidores MCP', chat: 'Chat', newChat: 'Nuevo Chat', signOut: 'Cerrar Sesión', toolchainAI: 'ToolChain AI', welcomeSubtitle: 'Conecta servidores MCP y chatea con un agente de IA.', connectedInfo: '{count} servidor(es) MCP conectado(s)', noConversations: 'Aún no hay conversaciones', newConversation: 'Nueva conversación', today: 'Hoy', yesterday: 'Ayer', thisWeek: 'Esta semana', older: 'Más antiguas', goodMorning: 'Buenos días', goodAfternoon: 'Buenas tardes', goodEvening: 'Buenas noches', activeReady: 'activos y listos', waitingConnections: 'esperando conexiones', serversConnected: '{count} servidor{s} conectado{s} y procesando.', connectToStart: 'Conecta un servidor MCP para empezar.', quickActions: 'Acciones rápidas', addServer: 'Añadir servidor', startConversation: 'Inicia una conversación con la IA', registerNewMcp: 'Registrar un nuevo servidor MCP', manageServers: 'Gestionar servidores', viewConfigureMcps: 'Ver y configurar MCPs', activityOverview: 'Resumen de actividad', weeklyActivity: 'Actividad semanal', messages: 'Mensajes', sessions: 'Sesiones', totalMessages: 'Mensajes totales', totalSessions: 'Sesiones totales', uptime: 'Tiempo activo', health: 'Estado', viewAll: 'Ver todo', noServersRegistered: 'Aún no hay servidores registrados', registerServer: 'Registrar servidor', active: 'Activo', offline: 'Desconectado', moreServers: '+{count} servidores más', recentChats: 'Chats recientes', startChat: 'Iniciar chat', aiPowerTips: 'Consejos pro de IA', getMoreFromAi: 'Sacar más partido a ToolChain AI', multiLanguageSupport: 'Compatibilidad multilingüe', multiLanguageDesc: 'Chatea en inglés, urdu, hindi o mixto — la IA lo entiende todo', bulkActions: 'Acciones masivas', bulkActionsDesc: 'Di «muévete todos los correos de X a la papelera» — la IA gestiona tareas en varios pasos', smartSearch: 'Búsqueda inteligente', smartSearchDesc: 'Usa sintaxis de Gmail: "from:x@y.com", "newer_than:7d"', tryItNow: 'Pruébalo ahora', systemsOnline: 'Sistemas en línea', suggestion1: '¿Qué herramientas hay disponibles?', suggestion2: 'Háblame de los servidores MCP conectados', suggestion3: '¿En qué puedes ayudarme?', suggestion4: 'Ejecuta una prueba rápida con las herramientas disponibles', typeMessage: 'Escribe un mensaje...', serversRunning: '{connected}/{total} servidores en ejecución', toolExecution: 'Ejecución de Herramientas', toolExecSubtitle: 'Probar y ejecutar herramientas MCP directamente', noConnectedMcps: 'Sin servidores conectados', noConnectedMcpsDesc: 'Conecte un servidor MCP primero para probar sus herramientas aquí.', goToMcpServers: 'Ir a Servidores MCP',
  },
  fr: {
    settings: 'Paramètres', customize: 'Personnalisez votre expérience', general: 'Général', account: 'Compte', security: 'Sécurité', chatSessions: 'Sessions de Chat', appearance: 'Apparence', lightTheme: 'Clair', darkTheme: 'Sombre', lightDesc: 'Interface propre et lumineuse', darkDesc: 'Agréable pour les yeux', language: 'Langue', selectLanguage: 'Sélectionnez votre langue préférée', accentColor: "Couleur d'accent", customizeAccent: "Personnaliser les couleurs de l'app", defaultColor: 'Par défaut', personalInfo: 'Informations Personnelles', viewDetails: 'Voir vos détails', email: 'E-mail', username: "Nom d'utilisateur", fullName: 'Nom Complet', notSet: 'Non défini', memberSince: 'Membre depuis', manageCredentials: 'Gérer vos identifiants', changeUsername: "Changer le nom d'utilisateur", changePassword: 'Changer le mot de passe', updatePassword: 'Mettre à jour votre mot de passe', newUsername: "Nouveau nom d'utilisateur", enterNewUsername: "Entrez le nouveau nom d'utilisateur", save: 'Enregistrer', cancel: 'Annuler', currentPassword: 'Mot de passe actuel', enterCurrentPassword: 'Entrez le mot de passe actuel', newPassword: 'Nouveau mot de passe', enterNewPassword: 'Entrez le nouveau mot de passe', confirmNewPassword: 'Confirmer le mot de passe', confirmNewPasswordPlaceholder: 'Confirmer le nouveau mot de passe', updatePasswordBtn: 'Mettre à jour', passwordsDontMatch: 'Les mots de passe ne correspondent pas', passwordSameAsCurrent: 'Le nouveau mot de passe doit être différent', exportOrDelete: 'Exporter ou supprimer vos conversations', exportAllChats: 'Exporter Tous les Chats', downloadWord: 'Télécharger en document Word', exportDesc: 'Exporter toutes les conversations en fichier <strong>.docx</strong>.', export: 'Exporter', deleteAllChats: 'Supprimer Tous les Chats', permanentlyRemove: 'Supprimer définitivement', deleteWarning: 'Cette action est <strong>permanente</strong> et irréversible.', typeDelete: 'Tapez <strong>DELETE</strong> pour confirmer', deleteAll: 'Tout Supprimer', done: 'Terminé', pleaseWait: 'Veuillez patienter...', chars8: '8+ caractères', uppercase: 'Majuscules', lowercase: 'Minuscules', number: 'Chiffre', specialChar: 'Caractère spécial', dashboard: 'Tableau de bord', mcpServers: 'Serveurs MCP', chat: 'Chat', newChat: 'Nouveau Chat', signOut: 'Déconnexion', toolchainAI: 'ToolChain AI', welcomeSubtitle: 'Connectez des serveurs MCP et discutez avec un agent IA.', connectedInfo: '{count} serveur(s) MCP connecté(s)', noConversations: 'Pas encore de conversations', newConversation: 'Nouvelle conversation', today: "Aujourd'hui", yesterday: 'Hier', thisWeek: 'Cette semaine', older: 'Plus anciennes', goodMorning: 'Bonjour', goodAfternoon: 'Bon après-midi', goodEvening: 'Bonsoir', activeReady: 'actifs et prêts', waitingConnections: 'en attente de connexions', serversConnected: '{count} serveur{s} connecté{s} et en traitement.', connectToStart: 'Connectez un serveur MCP pour commencer.', quickActions: 'Actions rapides', addServer: 'Ajouter un serveur', startConversation: 'Démarrer une conversation avec l’IA', registerNewMcp: 'Enregistrer un nouveau serveur MCP', manageServers: 'Gérer les serveurs', viewConfigureMcps: 'Voir et configurer les MCP', activityOverview: "Vue d’ensemble de l’activité", weeklyActivity: 'Activité hebdomadaire', messages: 'Messages', sessions: 'Sessions', totalMessages: 'Total des messages', totalSessions: 'Total des sessions', uptime: 'Temps de fonctionnement', health: 'État', viewAll: 'Tout voir', noServersRegistered: 'Aucun serveur enregistré pour le moment', registerServer: 'Enregistrer un serveur', active: 'Actif', offline: 'Hors ligne', moreServers: '+{count} serveurs supplémentaires', recentChats: 'Chats récents', startChat: 'Démarrer le chat', aiPowerTips: 'Astuces IA', getMoreFromAi: 'Tirez plus de ToolChain AI', multiLanguageSupport: 'Prise en charge multilingue', multiLanguageDesc: 'Chattez en anglais, ourdou, hindi ou mélangé — l’IA comprend tout', bulkActions: 'Actions groupées', bulkActionsDesc: 'Dites « mets tous les e-mails de X à la corbeille » — l’IA gère les tâches en plusieurs étapes', smartSearch: 'Recherche intelligente', smartSearchDesc: 'Syntaxe Gmail : "from:x@y.com", "newer_than:7d"', tryItNow: 'Essayer maintenant', systemsOnline: 'Systèmes en ligne', suggestion1: 'Quels outils sont disponibles ?', suggestion2: 'Parlez-moi des serveurs MCP connectés', suggestion3: 'Comment pouvez-vous m’aider ?', suggestion4: 'Lancez un test rapide avec les outils disponibles', typeMessage: 'Saisissez un message...', serversRunning: '{connected}/{total} serveurs actifs', toolExecution: 'Exécution d\'Outils', toolExecSubtitle: 'Tester et exécuter les outils MCP directement', noConnectedMcps: 'Aucun serveur connecté', noConnectedMcpsDesc: 'Connectez d\'abord un serveur MCP pour tester ses outils ici.', goToMcpServers: 'Aller aux Serveurs MCP',
  },
  de: {
    settings: 'Einstellungen', customize: 'Passen Sie Ihre Erfahrung an', general: 'Allgemein', account: 'Konto', security: 'Sicherheit', chatSessions: 'Chat-Sitzungen', appearance: 'Aussehen', lightTheme: 'Hell', darkTheme: 'Dunkel', lightDesc: 'Saubere und helle Oberfläche', darkDesc: 'Augenschonend', language: 'Sprache', selectLanguage: 'Wählen Sie Ihre bevorzugte Sprache', accentColor: 'Akzentfarbe', customizeAccent: 'App-Farben anpassen', defaultColor: 'Standard', personalInfo: 'Persönliche Informationen', viewDetails: 'Ihre Details anzeigen', email: 'E-Mail', username: 'Benutzername', fullName: 'Vollständiger Name', notSet: 'Nicht festgelegt', memberSince: 'Mitglied seit', manageCredentials: 'Anmeldedaten verwalten', changeUsername: 'Benutzername ändern', changePassword: 'Passwort ändern', updatePassword: 'Ihr Passwort aktualisieren', newUsername: 'Neuer Benutzername', enterNewUsername: 'Neuen Benutzernamen eingeben', save: 'Speichern', cancel: 'Abbrechen', currentPassword: 'Aktuelles Passwort', enterCurrentPassword: 'Aktuelles Passwort eingeben', newPassword: 'Neues Passwort', enterNewPassword: 'Neues Passwort eingeben', confirmNewPassword: 'Passwort bestätigen', confirmNewPasswordPlaceholder: 'Neues Passwort bestätigen', updatePasswordBtn: 'Passwort aktualisieren', passwordsDontMatch: 'Passwörter stimmen nicht überein', passwordSameAsCurrent: 'Neues Passwort muss sich unterscheiden', exportOrDelete: 'Gespräche exportieren oder löschen', exportAllChats: 'Alle Chats exportieren', downloadWord: 'Als Word-Dokument herunterladen', exportDesc: 'Alle Gespräche als <strong>.docx</strong> exportieren.', export: 'Exportieren', deleteAllChats: 'Alle Chats löschen', permanentlyRemove: 'Dauerhaft entfernen', deleteWarning: 'Diese Aktion ist <strong>dauerhaft</strong> und kann nicht rückgängig gemacht werden.', typeDelete: 'Geben Sie <strong>DELETE</strong> ein zur Bestätigung', deleteAll: 'Alle löschen', done: 'Fertig', pleaseWait: 'Bitte warten...', chars8: '8+ Zeichen', uppercase: 'Großbuchstaben', lowercase: 'Kleinbuchstaben', number: 'Zahl', specialChar: 'Sonderzeichen', dashboard: 'Dashboard', mcpServers: 'MCP-Server', chat: 'Chat', newChat: 'Neuer Chat', signOut: 'Abmelden', toolchainAI: 'ToolChain AI', welcomeSubtitle: 'Verbinden Sie MCP-Server und chatten Sie mit einem KI-Agenten.', connectedInfo: '{count} MCP-Server verbunden', noConversations: 'Noch keine Unterhaltungen', newConversation: 'Neue Unterhaltung', today: 'Heute', yesterday: 'Gestern', thisWeek: 'Diese Woche', older: 'Älter', goodMorning: 'Guten Morgen', goodAfternoon: 'Guten Tag', goodEvening: 'Guten Abend', activeReady: 'aktiv und bereit', waitingConnections: 'warten auf Verbindungen', serversConnected: '{count} Server{s} verbunden und in Verarbeitung.', connectToStart: 'Verbinden Sie einen MCP-Server, um zu starten.', quickActions: 'Schnellaktionen', addServer: 'Server hinzufügen', startConversation: 'Unterhaltung mit KI beginnen', registerNewMcp: 'Neuen MCP-Server registrieren', manageServers: 'Server verwalten', viewConfigureMcps: 'MCPs anzeigen und konfigurieren', activityOverview: 'Aktivitätsübersicht', weeklyActivity: 'Wöchentliche Aktivität', messages: 'Nachrichten', sessions: 'Sitzungen', totalMessages: 'Nachrichten gesamt', totalSessions: 'Sitzungen gesamt', uptime: 'Betriebszeit', health: 'Zustand', viewAll: 'Alle anzeigen', noServersRegistered: 'Noch keine Server registriert', registerServer: 'Server registrieren', active: 'Aktiv', offline: 'Offline', moreServers: '+{count} weitere Server', recentChats: 'Letzte Chats', startChat: 'Chat starten', aiPowerTips: 'KI-Profi-Tipps', getMoreFromAi: 'Mehr aus ToolChain AI holen', multiLanguageSupport: 'Mehrsprachige Unterstützung', multiLanguageDesc: 'Chatten Sie auf Englisch, Urdu, Hindi oder gemischt — die KI versteht alles', bulkActions: 'Massenaktionen', bulkActionsDesc: 'Sagen Sie „alle E-Mails von X in den Papierkorb“ — die KI erledigt mehrstufige Aufgaben', smartSearch: 'Intelligente Suche', smartSearchDesc: 'Gmail-Syntax: „from:x@y.com“, „newer_than:7d“', tryItNow: 'Jetzt ausprobieren', systemsOnline: 'Systeme online', suggestion1: 'Welche Tools sind verfügbar?', suggestion2: 'Erzähl mir von den verbundenen MCP-Servern', suggestion3: 'Wobei kannst du mir helfen?', suggestion4: 'Führe einen kurzen Test mit den verfügbaren Tools aus', typeMessage: 'Nachricht eingeben...', serversRunning: '{connected}/{total} Server aktiv', toolExecution: 'Tool-Ausführung', toolExecSubtitle: 'MCP-Tools direkt testen und ausführen', noConnectedMcps: 'Keine verbundenen Server', noConnectedMcpsDesc: 'Verbinden Sie zuerst einen MCP-Server, um seine Tools hier zu testen.', goToMcpServers: 'Zu MCP-Servern',
  },
  pt: {
    settings: 'Configurações', customize: 'Personalize sua experiência', general: 'Geral', account: 'Conta', security: 'Segurança', chatSessions: 'Sessões de Chat', appearance: 'Aparência', lightTheme: 'Claro', darkTheme: 'Escuro', lightDesc: 'Interface limpa e brilhante', darkDesc: 'Confortável para os olhos', language: 'Idioma', selectLanguage: 'Selecione seu idioma preferido', accentColor: 'Cor de destaque', customizeAccent: 'Personalizar cores do app', defaultColor: 'Padrão', personalInfo: 'Informações Pessoais', viewDetails: 'Ver seus detalhes', email: 'E-mail', username: 'Usuário', fullName: 'Nome Completo', notSet: 'Não definido', memberSince: 'Membro desde', manageCredentials: 'Gerenciar credenciais', changeUsername: 'Alterar Usuário', changePassword: 'Alterar Senha', updatePassword: 'Atualize sua senha', newUsername: 'Novo Usuário', enterNewUsername: 'Digite novo usuário', save: 'Salvar', cancel: 'Cancelar', currentPassword: 'Senha Atual', enterCurrentPassword: 'Digite a senha atual', newPassword: 'Nova Senha', enterNewPassword: 'Digite a nova senha', confirmNewPassword: 'Confirmar Senha', confirmNewPasswordPlaceholder: 'Confirmar nova senha', updatePasswordBtn: 'Atualizar Senha', passwordsDontMatch: 'Senhas não coincidem', passwordSameAsCurrent: 'Nova senha deve ser diferente da atual', exportOrDelete: 'Exportar ou excluir conversas', exportAllChats: 'Exportar Todos os Chats', downloadWord: 'Baixar como documento Word', exportDesc: 'Exportar todas as conversas para <strong>.docx</strong>.', export: 'Exportar', deleteAllChats: 'Excluir Todos os Chats', permanentlyRemove: 'Remover permanentemente', deleteWarning: 'Esta ação é <strong>permanente</strong> e irreversível.', typeDelete: 'Digite <strong>DELETE</strong> para confirmar', deleteAll: 'Excluir Tudo', done: 'Concluído', pleaseWait: 'Aguarde...', chars8: '8+ caracteres', uppercase: 'Maiúsculas', lowercase: 'Minúsculas', number: 'Número', specialChar: 'Caractere especial', dashboard: 'Painel', mcpServers: 'Servidores MCP', chat: 'Chat', newChat: 'Novo Chat', signOut: 'Sair', toolchainAI: 'ToolChain AI', welcomeSubtitle: 'Conecte servidores MCP e converse com um agente de IA.', connectedInfo: '{count} servidor(es) MCP conectado(s)', noConversations: 'Ainda não há conversas', newConversation: 'Nova conversa', today: 'Hoje', yesterday: 'Ontem', thisWeek: 'Esta semana', older: 'Mais antigas', goodMorning: 'Bom dia', goodAfternoon: 'Boa tarde', goodEvening: 'Boa noite', activeReady: 'ativos e prontos', waitingConnections: 'aguardando conexões', serversConnected: '{count} servidor{s} conectado{s} e processando.', connectToStart: 'Conecte um servidor MCP para começar.', quickActions: 'Ações rápidas', addServer: 'Adicionar servidor', startConversation: 'Inicie uma conversa com a IA', registerNewMcp: 'Registrar um novo servidor MCP', manageServers: 'Gerenciar servidores', viewConfigureMcps: 'Ver e configurar MCPs', activityOverview: 'Visão geral da atividade', weeklyActivity: 'Atividade semanal', messages: 'Mensagens', sessions: 'Sessões', totalMessages: 'Total de mensagens', totalSessions: 'Total de sessões', uptime: 'Tempo de atividade', health: 'Status', viewAll: 'Ver tudo', noServersRegistered: 'Nenhum servidor registrado ainda', registerServer: 'Registrar servidor', active: 'Ativo', offline: 'Offline', moreServers: '+{count} servidores a mais', recentChats: 'Chats recentes', startChat: 'Iniciar chat', aiPowerTips: 'Dicas avançadas de IA', getMoreFromAi: 'Tire mais do ToolChain AI', multiLanguageSupport: 'Suporte a vários idiomas', multiLanguageDesc: 'Converse em inglês, urdu, hindi ou misturado — a IA entende tudo', bulkActions: 'Ações em massa', bulkActionsDesc: 'Diga “mova todos os e-mails de X para a lixeira” — a IA cuida de tarefas em várias etapas', smartSearch: 'Busca inteligente', smartSearchDesc: 'Use sintaxe do Gmail: "from:x@y.com", "newer_than:7d"', tryItNow: 'Experimente agora', systemsOnline: 'Sistemas online', suggestion1: 'Quais ferramentas estão disponíveis?', suggestion2: 'Fale-me sobre os servidores MCP conectados', suggestion3: 'Como você pode me ajudar?', suggestion4: 'Execute um teste rápido com as ferramentas disponíveis', typeMessage: 'Digite uma mensagem...', serversRunning: '{connected}/{total} servidores em execução', toolExecution: 'Execução de Ferramentas', toolExecSubtitle: 'Testar e executar ferramentas MCP diretamente', noConnectedMcps: 'Nenhum servidor conectado', noConnectedMcpsDesc: 'Conecte primeiro um servidor MCP para testar suas ferramentas aqui.', goToMcpServers: 'Ir para Servidores MCP',
  },
  tr: {
    settings: 'Ayarlar', customize: 'Deneyiminizi özelleştirin', general: 'Genel', account: 'Hesap', security: 'Güvenlik', chatSessions: 'Sohbet Oturumları', appearance: 'Görünüm', lightTheme: 'Açık', darkTheme: 'Koyu', lightDesc: 'Temiz ve parlak arayüz', darkDesc: 'Göz dostu', language: 'Dil', selectLanguage: 'Tercih ettiğiniz dili seçin', accentColor: 'Vurgu Rengi', customizeAccent: 'Uygulama renklerini özelleştirin', defaultColor: 'Varsayılan', personalInfo: 'Kişisel Bilgiler', viewDetails: 'Detaylarınızı görün', email: 'E-posta', username: 'Kullanıcı Adı', fullName: 'Ad Soyad', notSet: 'Ayarlanmadı', memberSince: 'Üyelik Tarihi', manageCredentials: 'Kimlik bilgilerinizi yönetin', changeUsername: 'Kullanıcı Adı Değiştir', changePassword: 'Şifre Değiştir', updatePassword: 'Şifrenizi güncelleyin', newUsername: 'Yeni Kullanıcı Adı', enterNewUsername: 'Yeni kullanıcı adı girin', save: 'Kaydet', cancel: 'İptal', currentPassword: 'Mevcut Şifre', enterCurrentPassword: 'Mevcut şifrenizi girin', newPassword: 'Yeni Şifre', enterNewPassword: 'Yeni şifre girin', confirmNewPassword: 'Şifreyi Onayla', confirmNewPasswordPlaceholder: 'Yeni şifreyi onaylayın', updatePasswordBtn: 'Şifreyi Güncelle', passwordsDontMatch: 'Şifreler eşleşmiyor', passwordSameAsCurrent: 'Yeni şifre mevcut şifreden farklı olmalı', exportOrDelete: 'Sohbetlerinizi dışa aktarın veya silin', exportAllChats: 'Tüm Sohbetleri Dışa Aktar', downloadWord: 'Word belgesi olarak indir', exportDesc: 'Tüm sohbetleri <strong>.docx</strong> dosyasına aktarın.', export: 'Dışa Aktar', deleteAllChats: 'Tüm Sohbetleri Sil', permanentlyRemove: 'Kalıcı olarak kaldır', deleteWarning: 'Bu işlem <strong>kalıcıdır</strong> ve geri alınamaz.', typeDelete: 'Onaylamak için <strong>DELETE</strong> yazın', deleteAll: 'Tümünü Sil', done: 'Bitti', pleaseWait: 'Lütfen bekleyin...', chars8: '8+ karakter', uppercase: 'Büyük harf', lowercase: 'Küçük harf', number: 'Sayı', specialChar: 'Özel karakter', dashboard: 'Gösterge Paneli', mcpServers: 'MCP Sunucuları', chat: 'Sohbet', newChat: 'Yeni Sohbet', signOut: 'Çıkış', toolchainAI: 'ToolChain AI', welcomeSubtitle: 'MCP sunucularını bağlayın ve AI ajanıyla sohbet edin.', connectedInfo: '{count} MCP sunucu bağlı', noConversations: 'Henüz sohbet yok', newConversation: 'Yeni sohbet', today: 'Bugün', yesterday: 'Dün', thisWeek: 'Bu hafta', older: 'Daha eski', goodMorning: 'Günaydın', goodAfternoon: 'İyi öğlenler', goodEvening: 'İyi akşamlar', activeReady: 'aktif ve hazır', waitingConnections: 'bağlantı bekliyor', serversConnected: '{count} sunucu{s} bağlı ve işleniyor.', connectToStart: 'Başlamak için bir MCP sunucusu bağlayın.', quickActions: 'Hızlı işlemler', addServer: 'Sunucu ekle', startConversation: 'Yapay zeka ile sohbete başlayın', registerNewMcp: 'Yeni MCP sunucusu kaydedin', manageServers: 'Sunucuları yönet', viewConfigureMcps: 'MCP’leri görüntüle ve yapılandır', activityOverview: 'Etkinlik özeti', weeklyActivity: 'Haftalık etkinlik', messages: 'Mesajlar', sessions: 'Oturumlar', totalMessages: 'Toplam mesaj', totalSessions: 'Toplam oturum', uptime: 'Çalışma süresi', health: 'Sağlık', viewAll: 'Tümünü gör', noServersRegistered: 'Henüz kayıtlı sunucu yok', registerServer: 'Sunucu kaydet', active: 'Aktif', offline: 'Çevrimdışı', moreServers: '+{count} sunucu daha', recentChats: 'Son sohbetler', startChat: 'Sohbete başla', aiPowerTips: 'YZ ipuçları', getMoreFromAi: 'ToolChain AI’dan daha fazlasını alın', multiLanguageSupport: 'Çok dilli destek', multiLanguageDesc: 'İngilizce, Urduca, Hintçe veya karışık yazın — yapay zeka hepsini anlar', bulkActions: 'Toplu işlemler', bulkActionsDesc: '“X’ten gelen tüm e-postaları çöpe at” deyin — yapay zeka çok adımlı görevleri halleder', smartSearch: 'Akıllı arama', smartSearchDesc: 'Gmail sözdizimi: "from:x@y.com", "newer_than:7d"', tryItNow: 'Şimdi dene', systemsOnline: 'Sistemler çevrimiçi', suggestion1: 'Hangi araçlar kullanılabilir?', suggestion2: 'Bağlı MCP sunucularından bahset', suggestion3: 'Bana nasıl yardımcı olabilirsin?', suggestion4: 'Mevcut araçlarla hızlı bir test çalıştır', typeMessage: 'Mesaj yazın...', serversRunning: '{connected}/{total} sunucu çalışıyor', toolExecution: 'Araç Çalıştırma', toolExecSubtitle: 'MCP araçlarını doğrudan test edin ve çalıştırın', noConnectedMcps: 'Bağlı sunucu yok', noConnectedMcpsDesc: 'Araçlarını test etmek için önce bir MCP sunucusu bağlayın.', goToMcpServers: 'MCP Sunucularına Git',
  },
  ja: {
    settings: '設定', customize: '体験をカスタマイズ', general: '一般', account: 'アカウント', security: 'セキュリティ', chatSessions: 'チャットセッション', appearance: '外観', lightTheme: 'ライト', darkTheme: 'ダーク', lightDesc: 'クリーンで明るいインターフェース', darkDesc: '目に優しい', language: '言語', selectLanguage: 'お好みの言語を選択', accentColor: 'アクセントカラー', customizeAccent: 'アプリの色をカスタマイズ', defaultColor: 'デフォルト', personalInfo: '個人情報', viewDetails: '詳細を表示', email: 'メール', username: 'ユーザー名', fullName: 'フルネーム', notSet: '未設定', memberSince: '登録日', manageCredentials: '認証情報を管理', changeUsername: 'ユーザー名を変更', changePassword: 'パスワードを変更', updatePassword: 'パスワードを更新', newUsername: '新しいユーザー名', enterNewUsername: '新しいユーザー名を入力', save: '保存', cancel: 'キャンセル', currentPassword: '現在のパスワード', enterCurrentPassword: '現在のパスワードを入力', newPassword: '新しいパスワード', enterNewPassword: '新しいパスワードを入力', confirmNewPassword: 'パスワード確認', confirmNewPasswordPlaceholder: '新しいパスワードを確認', updatePasswordBtn: 'パスワード更新', passwordsDontMatch: 'パスワードが一致しません', passwordSameAsCurrent: '新しいパスワードは現在のものと異なる必要があります', exportOrDelete: '会話のエクスポートまたは削除', exportAllChats: 'すべてのチャットをエクスポート', downloadWord: 'Word文書としてダウンロード', exportDesc: 'すべての会話を<strong>.docx</strong>ファイルにエクスポート。', export: 'エクスポート', deleteAllChats: 'すべてのチャットを削除', permanentlyRemove: 'すべての会話を完全に削除', deleteWarning: 'この操作は<strong>永久的</strong>で元に戻せません。', typeDelete: '確認のため<strong>DELETE</strong>と入力', deleteAll: 'すべて削除', done: '完了', pleaseWait: 'お待ちください...', chars8: '8文字以上', uppercase: '大文字', lowercase: '小文字', number: '数字', specialChar: '特殊文字', dashboard: 'ダッシュボード', mcpServers: 'MCPサーバー', chat: 'チャット', newChat: '新しいチャット', signOut: 'サインアウト', toolchainAI: 'ToolChain AI', welcomeSubtitle: 'MCPサーバーに接続してAIエージェントとチャット。', connectedInfo: '{count}台のMCPサーバー接続済み', noConversations: 'まだ会話がありません', newConversation: '新しい会話', today: '今日', yesterday: '昨日', thisWeek: '今週', older: 'それ以前', goodMorning: 'おはようございます', goodAfternoon: 'こんにちは', goodEvening: 'こんばんは', activeReady: 'アクティブで準備完了', waitingConnections: '接続待ち', serversConnected: '{count} 台のサーバー{s}が接続され処理中です。', connectToStart: '始めるには MCP サーバーを接続してください。', quickActions: 'クイックアクション', addServer: 'サーバーを追加', startConversation: 'AI と会話を始める', registerNewMcp: '新しい MCP サーバーを登録', manageServers: 'サーバーを管理', viewConfigureMcps: 'MCP を表示・設定', activityOverview: 'アクティビティ概要', weeklyActivity: '週次アクティビティ', messages: 'メッセージ', sessions: 'セッション', totalMessages: 'メッセージ合計', totalSessions: 'セッション合計', uptime: '稼働時間', health: 'ヘルス', viewAll: 'すべて表示', noServersRegistered: 'まだサーバーが登録されていません', registerServer: 'サーバーを登録', active: 'アクティブ', offline: 'オフライン', moreServers: '+{count} 台の追加サーバー', recentChats: '最近のチャット', startChat: 'チャットを開始', aiPowerTips: 'AI 活用のヒント', getMoreFromAi: 'ToolChain AI をさらに活用', multiLanguageSupport: '多言語サポート', multiLanguageDesc: '英語、ウルドゥー語、ヒンディー語、混じり文でもチャットできます — AI がすべて理解します', bulkActions: '一括操作', bulkActionsDesc: '「X からのメールをすべてゴミ箱へ」のように伝えると — AI が複数ステップのタスクを処理します', smartSearch: 'スマート検索', smartSearchDesc: 'Gmail 構文を使用: "from:x@y.com", "newer_than:7d"', tryItNow: '今すぐ試す', systemsOnline: 'システムはオンライン', suggestion1: '利用できるツールは何ですか？', suggestion2: '接続されている MCP サーバーについて教えて', suggestion3: '何を手伝ってくれますか？', suggestion4: '利用可能なツールで簡単なテストを実行して', typeMessage: 'メッセージを入力...', serversRunning: '{connected}/{total} 台のサーバーが実行中', toolExecution: 'ツール実行', toolExecSubtitle: 'MCPツールを直接テスト・実行', noConnectedMcps: '接続されたサーバーがありません', noConnectedMcpsDesc: 'ツールをテストするには、まずMCPサーバーを接続してください。', goToMcpServers: 'MCPサーバーへ',
  },
  ko: {
    settings: '설정', customize: '경험을 맞춤 설정하세요', general: '일반', account: '계정', security: '보안', chatSessions: '채팅 세션', appearance: '외관', lightTheme: '라이트', darkTheme: '다크', lightDesc: '깔끔하고 밝은 인터페이스', darkDesc: '눈에 편안한', language: '언어', selectLanguage: '선호하는 언어를 선택하세요', accentColor: '강조 색상', customizeAccent: '앱 색상 맞춤 설정', defaultColor: '기본', personalInfo: '개인 정보', viewDetails: '세부 정보 보기', email: '이메일', username: '사용자명', fullName: '전체 이름', notSet: '미설정', memberSince: '가입일', manageCredentials: '자격 증명 관리', changeUsername: '사용자명 변경', changePassword: '비밀번호 변경', updatePassword: '비밀번호 업데이트', newUsername: '새 사용자명', enterNewUsername: '새 사용자명 입력', save: '저장', cancel: '취소', currentPassword: '현재 비밀번호', enterCurrentPassword: '현재 비밀번호 입력', newPassword: '새 비밀번호', enterNewPassword: '새 비밀번호 입력', confirmNewPassword: '비밀번호 확인', confirmNewPasswordPlaceholder: '새 비밀번호 확인', updatePasswordBtn: '비밀번호 업데이트', passwordsDontMatch: '비밀번호가 일치하지 않습니다', passwordSameAsCurrent: '새 비밀번호는 현재 비밀번호와 달라야 합니다', exportOrDelete: '대화 내보내기 또는 삭제', exportAllChats: '모든 채팅 내보내기', downloadWord: 'Word 문서로 다운로드', exportDesc: '모든 대화를 <strong>.docx</strong> 파일로 내보내기.', export: '내보내기', deleteAllChats: '모든 채팅 삭제', permanentlyRemove: '모든 대화 영구 삭제', deleteWarning: '이 작업은 <strong>영구적</strong>이며 되돌릴 수 없습니다.', typeDelete: '확인을 위해 <strong>DELETE</strong> 입력', deleteAll: '전체 삭제', done: '완료', pleaseWait: '잠시 기다려주세요...', chars8: '8자 이상', uppercase: '대문자', lowercase: '소문자', number: '숫자', specialChar: '특수문자', dashboard: '대시보드', mcpServers: 'MCP 서버', chat: '채팅', newChat: '새 채팅', signOut: '로그아웃', toolchainAI: 'ToolChain AI', welcomeSubtitle: 'MCP 서버를 연결하고 AI 에이전트와 채팅하세요.', connectedInfo: '{count}개 MCP 서버 연결됨', noConversations: '아직 대화가 없습니다', newConversation: '새 대화', today: '오늘', yesterday: '어제', thisWeek: '이번 주', older: '이전', goodMorning: '좋은 아침입니다', goodAfternoon: '안녕하세요', goodEvening: '좋은 저녁입니다', activeReady: '활성이며 준비됨', waitingConnections: '연결 대기 중', serversConnected: '{count}개 서버{s}가 연결되어 처리 중입니다.', connectToStart: '시작하려면 MCP 서버를 연결하세요.', quickActions: '빠른 작업', addServer: '서버 추가', startConversation: 'AI와 대화 시작하기', registerNewMcp: '새 MCP 서버 등록', manageServers: '서버 관리', viewConfigureMcps: 'MCP 보기 및 구성', activityOverview: '활동 개요', weeklyActivity: '주간 활동', messages: '메시지', sessions: '세션', totalMessages: '총 메시지', totalSessions: '총 세션', uptime: '가동 시간', health: '상태', viewAll: '모두 보기', noServersRegistered: '등록된 서버가 아직 없습니다', registerServer: '서버 등록', active: '활성', offline: '오프라인', moreServers: '+{count}개 서버 더', recentChats: '최근 채팅', startChat: '채팅 시작', aiPowerTips: 'AI 활용 팁', getMoreFromAi: 'ToolChain AI를 더 활용하기', multiLanguageSupport: '다국어 지원', multiLanguageDesc: '영어, 우르두어, 힌디어 또는 혼합으로 채팅 — AI가 모두 이해합니다', bulkActions: '일괄 작업', bulkActionsDesc: '“X에서 온 모든 메일 휴지통으로”라고 하면 — AI가 여러 단계 작업을 처리합니다', smartSearch: '스마트 검색', smartSearchDesc: 'Gmail 구문 사용: "from:x@y.com", "newer_than:7d"', tryItNow: '지금 사용해 보기', systemsOnline: '시스템 온라인', suggestion1: '어떤 도구를 사용할 수 있나요?', suggestion2: '연결된 MCP 서버에 대해 알려줘', suggestion3: '무엇을 도와줄 수 있나요?', suggestion4: '사용 가능한 도구로 빠른 테스트 실행', typeMessage: '메시지를 입력하세요...', serversRunning: '{connected}/{total}개 서버 실행 중', toolExecution: '도구 실행', toolExecSubtitle: 'MCP 도구를 직접 테스트하고 실행하세요', noConnectedMcps: '연결된 서버 없음', noConnectedMcpsDesc: '도구를 테스트하려면 먼저 MCP 서버를 연결하세요.', goToMcpServers: 'MCP 서버로 이동',
  },
  ru: {
    settings: 'Настройки', customize: 'Настройте свой опыт', general: 'Общие', account: 'Аккаунт', security: 'Безопасность', chatSessions: 'Сессии чата', appearance: 'Внешний вид', lightTheme: 'Светлая', darkTheme: 'Тёмная', lightDesc: 'Чистый и яркий интерфейс', darkDesc: 'Комфортно для глаз', language: 'Язык', selectLanguage: 'Выберите предпочитаемый язык', accentColor: 'Акцентный цвет', customizeAccent: 'Настроить цвета приложения', defaultColor: 'По умолчанию', personalInfo: 'Личная информация', viewDetails: 'Просмотр деталей', email: 'Эл. почта', username: 'Имя пользователя', fullName: 'Полное имя', notSet: 'Не задано', memberSince: 'Участник с', manageCredentials: 'Управление учётными данными', changeUsername: 'Изменить имя пользователя', changePassword: 'Изменить пароль', updatePassword: 'Обновить пароль аккаунта', newUsername: 'Новое имя пользователя', enterNewUsername: 'Введите новое имя', save: 'Сохранить', cancel: 'Отмена', currentPassword: 'Текущий пароль', enterCurrentPassword: 'Введите текущий пароль', newPassword: 'Новый пароль', enterNewPassword: 'Введите новый пароль', confirmNewPassword: 'Подтвердите пароль', confirmNewPasswordPlaceholder: 'Подтвердите новый пароль', updatePasswordBtn: 'Обновить пароль', passwordsDontMatch: 'Пароли не совпадают', passwordSameAsCurrent: 'Новый пароль должен отличаться', exportOrDelete: 'Экспорт или удаление бесед', exportAllChats: 'Экспорт всех чатов', downloadWord: 'Скачать как документ Word', exportDesc: 'Экспортировать все беседы в файл <strong>.docx</strong>.', export: 'Экспорт', deleteAllChats: 'Удалить все чаты', permanentlyRemove: 'Удалить навсегда', deleteWarning: 'Это действие <strong>необратимо</strong>.', typeDelete: 'Введите <strong>DELETE</strong> для подтверждения', deleteAll: 'Удалить всё', done: 'Готово', pleaseWait: 'Пожалуйста подождите...', chars8: '8+ символов', uppercase: 'Заглавные', lowercase: 'Строчные', number: 'Цифра', specialChar: 'Спец. символ', dashboard: 'Панель', mcpServers: 'MCP серверы', chat: 'Чат', newChat: 'Новый чат', signOut: 'Выход', toolchainAI: 'ToolChain AI', welcomeSubtitle: 'Подключайте MCP серверы и общайтесь с ИИ-агентом.', connectedInfo: '{count} MCP сервер(ов) подключено', noConversations: 'Пока нет разговоров', newConversation: 'Новый разговор', today: 'Сегодня', yesterday: 'Вчера', thisWeek: 'На этой неделе', older: 'Ранее', goodMorning: 'Доброе утро', goodAfternoon: 'Добрый день', goodEvening: 'Добрый вечер', activeReady: 'активны и готовы', waitingConnections: 'ожидание подключений', serversConnected: '{count} сервер{s} подключено и обрабатывает.', connectToStart: 'Подключите MCP-сервер, чтобы начать.', quickActions: 'Быстрые действия', addServer: 'Добавить сервер', startConversation: 'Начать беседу с ИИ', registerNewMcp: 'Зарегистрировать новый MCP-сервер', manageServers: 'Управление серверами', viewConfigureMcps: 'Просмотр и настройка MCP', activityOverview: 'Обзор активности', weeklyActivity: 'Активность за неделю', messages: 'Сообщения', sessions: 'Сессии', totalMessages: 'Всего сообщений', totalSessions: 'Всего сессий', uptime: 'Время работы', health: 'Состояние', viewAll: 'Показать все', noServersRegistered: 'Серверы ещё не зарегистрированы', registerServer: 'Зарегистрировать сервер', active: 'Активен', offline: 'Офлайн', moreServers: '+{count} других серверов', recentChats: 'Недавние чаты', startChat: 'Начать чат', aiPowerTips: 'Советы по ИИ', getMoreFromAi: 'Больше возможностей с ToolChain AI', multiLanguageSupport: 'Поддержка нескольких языков', multiLanguageDesc: 'Пишите на английском, урду, хинди или смешанно — ИИ всё понимает', bulkActions: 'Массовые действия', bulkActionsDesc: 'Скажите «все письма от X в корзину» — ИИ выполняет многошаговые задачи', smartSearch: 'Умный поиск', smartSearchDesc: 'Синтаксис Gmail: «from:x@y.com», «newer_than:7d»', tryItNow: 'Попробуйте сейчас', systemsOnline: 'Системы в сети', suggestion1: 'Какие инструменты доступны?', suggestion2: 'Расскажи о подключённых MCP-серверах', suggestion3: 'Чем ты можешь помочь?', suggestion4: 'Запусти быстрый тест доступными инструментами', typeMessage: 'Введите сообщение...', serversRunning: '{connected}/{total} серверов работает', toolExecution: 'Выполнение инструментов', toolExecSubtitle: 'Тестируйте и выполняйте инструменты MCP напрямую', noConnectedMcps: 'Нет подключённых серверов', noConnectedMcpsDesc: 'Сначала подключите MCP-сервер, чтобы тестировать его инструменты.', goToMcpServers: 'Перейти к MCP серверам',
  },
}

function getUserLanguage(userId) {
  if (!userId) return 'en'
  const stored = localStorage.getItem(STORAGE_PREFIX + userId)
  if (stored && translations[stored]) return stored
  return 'en'
}

export function useLanguage(userId) {
  const [language, setLanguageState] = useState(() => getUserLanguage(userId))
  const prevUserId = useRef(userId)

  useEffect(() => {
    if (prevUserId.current !== userId) {
      prevUserId.current = userId
      const lang = getUserLanguage(userId)
      setLanguageState(lang)
      document.documentElement.setAttribute('dir', ['ar', 'ur'].includes(lang) ? 'rtl' : 'ltr')
    }
  }, [userId])

  useEffect(() => {
    document.documentElement.setAttribute('dir', ['ar', 'ur'].includes(language) ? 'rtl' : 'ltr')
  }, [language])

  const setLanguage = useCallback((lang) => {
    setLanguageState(lang)
    if (userId) {
      localStorage.setItem(STORAGE_PREFIX + userId, lang)
    }
    document.documentElement.setAttribute('dir', ['ar', 'ur'].includes(lang) ? 'rtl' : 'ltr')
  }, [userId])

  const t = useCallback((key) => {
    return translations[language]?.[key] || translations.en[key] || key
  }, [language])

  return { language, setLanguage, t }
}
