"""add_user_id_title_to_chat_sessions

Revision ID: 6e3f8de34a6c
Revises: 7b453545e217
Create Date: 2026-05-02 14:50:24.820795

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6e3f8de34a6c'
down_revision: Union[str, Sequence[str], None] = '7b453545e217'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.add_column('chat_sessions', sa.Column('user_id', sa.String(length=36), nullable=True))
    op.add_column('chat_sessions', sa.Column('title', sa.String(length=255), nullable=True))

    op.execute("DELETE FROM messages WHERE session_id IN (SELECT id FROM chat_sessions WHERE user_id IS NULL)")
    op.execute("DELETE FROM chat_sessions WHERE user_id IS NULL")

    op.alter_column('chat_sessions', 'user_id', nullable=False)
    op.create_index(op.f('ix_chat_sessions_user_id'), 'chat_sessions', ['user_id'], unique=False)
    op.create_foreign_key('fk_chat_sessions_user_id', 'chat_sessions', 'users', ['user_id'], ['id'])


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_chat_sessions_user_id', 'chat_sessions', type_='foreignkey')
    op.drop_index(op.f('ix_chat_sessions_user_id'), table_name='chat_sessions')
    op.drop_column('chat_sessions', 'title')
    op.drop_column('chat_sessions', 'user_id')
    # ### end Alembic commands ###
